apiVersion: skaffold/v1beta13
build:
  artifacts:
  - context: .
    docker: {dockerfile: Dockerfile}
    image: gcr.io/mlops-workshop/cifar-tfx-image
  tagPolicy:
    envTemplate: {template: '{{.IMAGE_NAME}}:latest'}
kind: Config
